version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: aegis
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: aegis_iam
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
